application: foodbox
version:     1
runtime:     go
api_version: go1

handlers:
- url: /javascripts
  static_dir: ../public/javascripts
  
- url: /stylesheets
  static_dir: ../public/stylesheets
  
- url: /images
  static_dir: ../public/images
  
- url: /.*
  script: _go_app